name: FrostedEngineering
version: 0.0.1
api-version: 1.13
main: net.iceyleagons.frostedengineering.Main
authors: [TOTHTOMI,G4be_]
load: startup
website: https://www.iceyleagons.net/
description: An official expension for Frosted Essentials.
commands:
  tpxd:
    description: tpxd